apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  namespace: pihole
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.1.11 # My Homelab DNS
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp

    - port: 80
      targetPort: 80
      protocol: TCP
      name: webadmin
  selector:
    app: pihole